In [1]:
import dataloader
import numpy as np
import submoddiv as smd
import probit
import pandas as pd
import os

c:\anaconda2\envs\py3.6\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
from importlib import reload

reload(probit)
reload(smd)
reload(dataloader)

<module 'dataloader' from 'C:\\Columbia\\Courses\\AdvancedML\\advml\\dataloader.py'>

In [3]:
sparseAdWeights,adIds = dataloader.loadAdWeightsAndIds()
adIdsRev,convertToAdInx = dataloader.getAdIdConverterFunction(adIds)

In [4]:
def findNearestNeighbor(ad, wAds):
    diffs = wAds - ad
    norms = np.linalg.norm(diffs, axis=1)
    newAdIndex = np.argmin(norms)
    #   print(newAdIndex)
    return newAdIndex

In [54]:
def simulate(nUser, wAds, model, userInx, n=6):       
    submod = smd.SubModDivGlobal(nUser, wAds,model)
    
    wAds = wAds.toarray()
    
    subsets = np.empty((0, n))
    prevAds = np.empty(0)
    prevAdData = np.empty((0, wAds.shape[1]))
    print(prevAdData)

    total = np.zeros(wAds.shape[1])
    meanAd = np.zeros(wAds.shape[1])

    for i in range(0, 100):
        subset = submod.getSubSet(userInx, n)
        subsets = np.append(subsets, [subset], axis=0)
        
        newAdIndex = findNearestNeighbor(meanAd, wAds[subset])
        print(subset)
        print(newAdIndex)
        submod.registerClick(subset[newAdIndex])

        prevAds = np.append(prevAds, subset[newAdIndex])
        prevAdData = np.append(prevAdData, [wAds[subset[newAdIndex]]], axis=0)

        total = total + wAds[subset[newAdIndex]]
        meanAd = total/float(prevAdData.shape[0])

#         wAds[newAdIndex, :] = float("inf")
        #     print("NewAdIndex: {}, Total: {}, meanAd: {}".format(newAdIndex, total, meanAd))

    return prevAdData, prevAds, subsets

In [6]:
eventsDf = pd.read_csv('filtered_events.csv')

uniqUser = np.unique(eventsDf.uuid)
nUser = uniqUser.shape[0]

In [7]:
model = probit.createProbitModelGlobal(sparseAdWeights)

In [8]:
weights_filename = 'probit.h5'

if os.path.isfile(weights_filename):
    print("loading existing weights")
    model.load_weights(weights_filename)

loading existing weights


In [44]:
prevAdData.shape

(5, 96)

In [46]:
prevAdData, prevAds, subsets = simulate(nUser, sparseAdWeights, model, 5)
subsets

[]
[ 45609  94016    498  95538 107880  49415]
0
[45609  9523 81141   707  2287   505]
0
[45609 60257    53  1272 12301  5409]
0
[45609 35273   664 51954   784  2765]
0
[ 45609  60257  45211     23 112209    268]
0


array([[4.56090e+04, 9.40160e+04, 4.98000e+02, 9.55380e+04, 1.07880e+05,
        4.94150e+04],
       [4.56090e+04, 9.52300e+03, 8.11410e+04, 7.07000e+02, 2.28700e+03,
        5.05000e+02],
       [4.56090e+04, 6.02570e+04, 5.30000e+01, 1.27200e+03, 1.23010e+04,
        5.40900e+03],
       [4.56090e+04, 3.52730e+04, 6.64000e+02, 5.19540e+04, 7.84000e+02,
        2.76500e+03],
       [4.56090e+04, 6.02570e+04, 4.52110e+04, 2.30000e+01, 1.12209e+05,
        2.68000e+02]])

# Metrics

In [52]:
def accuracyAtK(subsets, adClickInx, nAds, model, userInx, k):
    probs = model.predict([
            np.array([userInx]*nAds),
            np.arange(nAds)
        ],batch_size=50000).ravel()
    
    accuracy = 0
    for i in range(subsets.shape[0]):
        topAds = sorted(subsets[i], key=lambda x: probs[x], reverse=True)[:k]
        if adClickInx[i] in topAds:
            accuracy = accuracy + 1
    
#     topAds = sorted(range(0, len(probs)), key=lambda x: prob[x], reverse=True)[:k]
    
#     common = set(adClickInx).intersection(set(topAds))
#     return len(common)/float(len(adClickInx))

    return accuracy/float(subsets.shape[0])

In [48]:
def meanClickProbability(subSets, model):
    probs = self.model.predict([
            np.array([userInx]*wAds.shape[0]),
            np.arange(wAds.shape[0])
        ],batch_size=50000).ravel()
    
    findSubSetProbs = np.vectorize(lambda subset: np.sum(probs[subset]))
    subSetProbs = findSubSetProbs(subSets)
    totalProb = np.sum(subSetProbs)
    return totalProb/float(len(subSetProbs))

In [5]:
eventsDf.columns

Index(['display_id', 'uuid', 'timestamp', 'ad_id', 'clicked', 'ad_inx',
       'user_inx'],
      dtype='object')

In [10]:
def findAdTrendingProbs(x):
#     print(len(x.loc[x['clicked'] == 1]))
#     print(float(len(x)))
    x['clickProb'] = len(x.loc[x['clicked'] == 1])/float(len(x))
#     print(x)
    return x

In [11]:
groups = eventsDf.groupby(by='ad_inx')

In [12]:
copy = groups.apply(lambda group: findAdTrendingProbs(group))

display_id            uuid   timestamp   ad_id  clicked  ad_inx  \
0                10  b09a0e92aa4d17         693  241662        0   66748   
1                10  b09a0e92aa4d17         693  332908        1   85384   
2                30  53ca43b326638b        2550  139944        1   42405   
3                30  53ca43b326638b        2550  166549        0   49228   
4                30  53ca43b326638b        2550  181548        0   52892   
5                30  53ca43b326638b        2550  250079        0   68169   
6                30  53ca43b326638b        2550  269017        0   71725   
7                79  9d376148017289        5793   79784        0   23656   
8                79  9d376148017289        5793   88711        0   26510   
9                79  9d376148017289        5793   92113        1   27594   
10               79  9d376148017289        5793  133677        0   40428   
11               79  9d376148017289        5793  150083        0   44896   
12               79  9d376148017289        5793  151832        0   45450   
13               79  9d376148017289        5793  187282        0   54255   
14              110  c64ac98a172430        8339   35573        0   10748   
15              110  c64ac98a172430        8339   41355        1   12492   
16              110  c64ac98a172430        8339   80053        0   23769   
17              110  c64ac98a172430        8339  150143        0   44905   
18              110  c64ac98a172430        8339  163597        0   48517   
19              110  c64ac98a172430        8339  304153        0   79085   
20              177  2d7b2cb3ffe639       13166   28629        0    8552   
21              177  2d7b2cb3ffe639       13166   29817        0    8944   
22              177  2d7b2cb3ffe639       13166   38763        0   11749   
23              177  2d7b2cb3ffe639       13166   50302        0   15115   
24              177  2d7b2cb3ffe639       13166  179727        1   52343   
25              229  fc514cfac3fd61       16513   10344        1    3295   
26              229  fc514cfac3fd61       16513   50854        0   15273   
27              229  fc514cfac3fd61       16513   78939        0   23397   
28              229  fc514cfac3fd61       16513  143294        0   43312   
29              229  fc514cfac3fd61       16513  150817        0   45119   
...             ...             ...         ...     ...      ...     ...   
2405044    16874314  a1addd0c083540  1123180928  472758        0  116624   
2405045    16874314  a1addd0c083540  1123180928  492732        0  120193   
2405046    16874314  a1addd0c083540  1123180928  527626        0  126645   
2405047    16874314  a1addd0c083540  1123180928  544134        0  128575   
2405048    16874323  99eb7af7d80d5a  1123181830     801        0     173   
2405049    16874323  99eb7af7d80d5a  1123181830   89720        1   26834   
2405050    16874323  99eb7af7d80d5a  1123181830  242487        0   67013   
2405051    16874323  99eb7af7d80d5a  1123181830  520363        0  125534   
2405052    16874324  bb525bd665167e  1123181862  139059        0   42154   
2405053    16874324  bb525bd665167e  1123181862  166804        1   49343   
2405054    16874324  bb525bd665167e  1123181862  171261        0   50523   
2405055    16874324  bb525bd665167e  1123181862  179041        0   52204   
2405056    16874324  bb525bd665167e  1123181862  499889        0  121823   
2405057    16874325  54d3719765768d  1123181920   54154        0   16126   
2405058    16874325  54d3719765768d  1123181920  134063        0   40542   
2405059    16874325  54d3719765768d  1123181920  144116        0   43575   
2405060    16874325  54d3719765768d  1123181920  289908        1   76272   
2405061    16874325  54d3719765768d  1123181920  525747        0  126279   
2405062    16874399  28438f752389c0  1123186031   56570        0   16801   
2405063    16874399  28438f752389c0  1123186031   56634        1   16810   
2405064    16874399  28438f752389c0  1123186031   56643  

In [13]:
copy = copy[['ad_inx', 'clickProb']].drop_duplicates()
copy

ad_inx  clickProb
0         66748   0.136364
1         85384   0.259259
2         42405   0.286573
3         49228   0.192308
4         52892   0.483051
5         68169   0.008658
6         71725   0.091703
7         23656   0.000000
8         26510   0.018750
9         27594   0.311741
10        40428   0.006173
11        44896   0.080768
12        45450   0.151515
13        54255   0.000000
14        10748   0.225000
15        12492   0.200000
16        23769   0.051724
17        44905   0.181495
18        48517   0.249249
19        79085   0.000000
20         8552   0.200692
21         8944   0.113622
22        11749   0.084211
23        15115   0.153846
24        52343   0.617978
25         3295   0.478088
26        15273   0.078313
27        23397   0.070175
28        43312   0.093220
29        45119   0.127820
...         ...        ...
2404540    1173   0.000000
2404608  119986   0.000000
2404668   35242   0.000000
2404718  128732   1.000000
2404727    5666   0.000000
2404747  125007   0.000000
2404754   44128   0.000000
2404756   94920   0.000000
2404768  105372   0.000000
2404771  118321   0.000000
2404776  109790   1.000000
2404814  118340   0.000000
2404825  117763   0.000000
2404831   70922   1.000000
2404838   93037   0.000000
2404863   68026   1.000000
2404873   58564   0.000000
2404883   57878   0.000000
2404887  128417   0.000000
2404893  128619   0.000000
2404896   46161   0.000000
2404907   73221   0.000000
2404908   75276   0.000000
2405009  125743   0.000000
2405019   64237   0.000000
2405063   16810   1.000000
2405064   16816   0.000000
2405065   29657   0.000000
2405068   61497   0.000000
2405069  119972   0.000000

[128904 rows x 2 columns]

In [14]:
ad_probs_array = np.zeros(len(copy))
# copy.apply(lambda row: ad_probs_array[row.ad_inx] = row.clickProb)
zipped = zip(copy.ad_inx, copy.clickProb)
for ad_inx, prob in zipped:
    ad_probs_array[ad_inx] = prob
ad_probs_array

array([0.        , 0.        , 0.26804124, ..., 1.        , 0.        ,
       0.        ])

In [15]:
np.unique(ad_probs_array)

array([0.        , 0.00327869, 0.00350877, ..., 0.875     , 0.88888889,
       1.        ])

In [17]:
import _pickle as pickle
pickle.dump(ad_probs_array, open('ad_probs.pickle', 'wb'))

In [59]:
def simTrendingAds(nUser, ad_probs, wAds, model, userInx, n=6):
    submod = smd.SubModDivGlobal(nUser, wAds,model)
    
    wAds = wAds.toarray()
    
    subsets = np.empty((0, n)) 
    prevAds = np.empty(0)
    prevAdData = np.empty((0, wAds.shape[1]))
    print(prevAdData)

#     total = np.zeros(wAds.shape[1])
#     meanAd = np.zeros(wAds.shape[1])

    for i in range(0, 100):
        subset = submod.getSubSet(userInx, n)
        subsets = np.append(subsets, [subset], axis=0)
        
        subsetProbs = ad_probs[subset]
        subsetProbs = subsetProbs/float(sum(subsetProbs))
        
        newAdIndex = selectAdWithProb(subsetProbs)
#         newAdIndex = findNearestNeighbor(meanAd, wAds[subset])
        print(subset)
        print(newAdIndex)
        submod.registerClick(subset[newAdIndex])

        prevAds = np.append(prevAds, subset[newAdIndex])
        prevAdData = np.append(prevAdData, [wAds[subset[newAdIndex]]], axis=0)

#         total = total + wAds[subset[newAdIndex]]
#         meanAd = total/float(prevAdData.shape[0])

#         wAds[newAdIndex, :] = float("inf")
        #     print("NewAdIndex: {}, Total: {}, meanAd: {}".format(newAdIndex, total, meanAd))

    return prevAdData, prevAds, subsets

In [60]:
def selectAdWithProb(ad_probs):
    return np.random.choice(range(0, len(ad_probs)), p=ad_probs)

In [62]:
prevAdData, prevAds, subsets = simTrendingAds(nUser, ad_probs_array, sparseAdWeights, model, 5)
subsets

[]
[ 45609  94016    498  95538 107880  49415]
1
[94016 55696  9523 81141   707  2287]
0
[94016 30130   582 76083  1272  5409]
0
[94016   284 42929 62428 89771  2765]
0
[94016 45211     9  4379    31   790]
0


In [53]:
accuracy = accuracyAtK(subsets, prevAds, sparseAdWeights.shape[0], model, 5, 2)
# accuracyAtK(subsets, adClickInx, wAds, model, userInx, k)
accuracy

ValueError: Error when checking model : the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[5],
       [5],
       [5],
       ...,
       [5],
       [5],
       [5]]), array([[     0],
       [     1],
       [     2],
       ...,
       [128901],
       [128902],
       [128903]]...